### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by imperatormandalina** [ENDERZOMBI102/JythonMC#1]
hello, sorry for the disturbance but i have some questions in my mind and didn't know where else to ask these questions.
i was just about to start learning java (as my first programming language) to develop minecraft mods but i also want to learn python, then when i opened modrinth, i saw this mod.
what is jythonmc? does it allow you to write code in python and convert it to java code that minecraft understands?
how good is it's performance?
is it complete?
can i do **anything** with it?
again, sorry for taking your time.

**Comment by ENDERZOMBI102** [comment]
hi!
this mod is a library, it’ll help modders who wants to use jython/python in mods, so by itself it doesn’t do anything.

if you have more questions, just ask, if not, close the issue
