### ISSUE TITLE
Many issues 

### ISSUE THREAD

**Issue by C10udburst** [ENDERZOMBI102/JythonMC#2]
There are a lot of inconsistencies in naming (`jython` or `jythonmc`)

1. [this line](https://github.com/ENDERZOMBI102/JythonMC/blob/944e28b60ceb7437eda3fc3c8c017fcf13b3f4a4/src/main/java/com/enderzombi102/jython/Jython.java#L38) should say `jythonmc`, because is crashes otherwise

Following the guide in README also causes crashes

2. `NoClassDefFoundError` is thrown because the package's name is `com.enderzombi102.jython` not `com.enderzombi102.jythonmc`
3. the guide should contain mention about adding `include implementation("org.python:jython:$jython_version")` to dependencies, as without that a `NoClassDefFoundError` will be thrown

Even after jumping through those hoops, I wasn't able to run jython interperter, as another error occured while trying to run `exec` from `PythonInterpreter`:
```
Cannot read field "modules" because the return value of "org.python.core.Py.getSystemState()" is null
```

If you want to see the code I tried, its [here](https://github.com/C10udburst/meteor-python-addon)

**Comment by ENDERZOMBI102** [comment]
1 and 2 are alredy fixed, i just forgot to publish a release with the fix
for 3, i have no idea why you need to include/depend on jython yourself, as imade it  a dependency of JythonMC... gotta look into that

**Comment by ENDERZOMBI102** [comment]
try to update to 1.0.1 and remove the jython dependency, it should all work now

**Comment by C10udburst** [comment]
> try to update to 1.0.1 and remove the jython dependency, it should all work now

I tried it, but it still crashes:
[crash-2021-06-20_19.25.48-client.txt](https://github.com/ENDERZOMBI102/JythonMC/files/6682816/crash-2021-06-20_19.25.48-client.txt)

**Comment by ENDERZOMBI102** [comment]
i can't test the client right now, but i've tested the server, and it works, does it  work for you? 
also gradle correctly pulls jython for me...

**Comment by ENDERZOMBI102** [comment]
no updates in the last 6 days, i’m gonna close this, if you still have trubles please reopen
